apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: my-image
      volumeMounts:
        - name: my-pvc-mount
          mountPath: /pathIII
  volumes:
    - name: my-pvc-mount
      persistentVolumeClaim:
        claimName: configmapII
