apiVersion: v1
kind: Pod
metadata:
  name: mypodII
spec:
  containers:
    - name: mycontainerII
      image: docker.io/alvinbanerjee/optimized1
      volumeMounts:
        - name: mypvcmountII
          mountPath: WORKDIR /app //mount path 
  volumes:
    - name: mypvcmountII
      configMap:
        name: configmap //the config map is mounted
