apiVersion: v1
kind: Pod
metadata:
  name: mypodII
spec:
  containers:
    - name: my-container
      image: my-image
      volumeMounts:
        - name: mypvcmountII
          mountPath: WORKDIR /app //mount path 
  volumes:
    - name: mypvcmountII
      configMap:
        name: configmap //the config map is mounted
