apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
initContainers:
    - name: init-container 
      image: your-image// the name of the image from the docker hub
      command: ["sh", "-c", "mkdir -p /pathIII"] //path created in the container
  containers:
    - name: my-container
      image: my-image
      volumeMounts:
        - name: mypvcmountII
          mountPath: /pathIII
  volumes:
    - name: mypvcmountII
     configMap:
        claimName: configmapII
