apiVersion: v1
kind: Pod
metadata:
  name: mypodIII
spec:

  containers:
    - name: my-container
      image: docker.io/alvinbanerjee/optimized2
      volumeMounts:
        - name: mypvcmountII
          mountPath: WORKDIR /app
  volumes:
    - name: mypvcmountII
     configMap:
        claimName: configmapII
