apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
initContainers:
    - name: init-container //the name of the image from the docker hub
      image: your-image// the name of the image from the docker hub
      command: ["sh", "-c", "mkdir -p /pathII"]
  containers:
    - name: my-container
      image: my-image
      volumeMounts:
        - name: my-pvc-mount
          mountPath: /pathII
  volumes:
    - name: my-pvc-mount
      configMap:
        name: configmap
